config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  #
  get "welcome" => "welcome#index"
  get "test" => "welcome#test"


  # 用户注册和登录登出
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout
  resources :cellphone_tokens, only: [:create]
  # mount RuCaptcha::Engine => "/rucaptcha"


  namespace :admin do
    resources :users
    resources :slider_photos do
      member do
      post :hide
      post :public
      end
    end
    
    resources :categories
    resources :products do
      resources :subproducts do
        member do
          post :update_weight
        end
      end
      resources :product_params
      resources :product_photos
    end

    resources :orders do
      member do
        get :ship_page
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    resources :lessons do
      resources :buyers
      resources :chapters
      resources :posts do
        member do
          post :update_weight
        end
      end

    end
  end



  resources :categories

  resources :products do
    member do
      post :add_to_cart
    end

    resources :evaluations do
      resources :evaluation_photos
    end
  end

  resources :carts do
    collection do
      delete :clean
        get :checkout
        post :update_cart
    end
  end

  resources :addresses do
    member do
      put :set_default_address
    end
  end

  resources :cart_items

  resources :orders do
    collection do
      post :build_order
      post :order_create
      post :lesson_order_create
    end
    member do
    post :pay_with_wechat
    post :pay_with_alipay
    post :apply_to_cancel
    post :order_create

  end
  end

  namespace :account do
    resources :orders do
      member do
        post :cancel
        post :shipped
      end
    end
  end

  resources :evaluations do
    resources :evaluation_photos
  end

  resources :payments, only: [:index] do
    member do
      post :create_payment
      get :create_payment
      post :get_payment_status
    end
    collection do
      get :generate_pay
      get :lesson_generat_pay
      post :pay_return
      post :pay_notify
      get :pay_notify
      get :pay_return
      post :test
      get :success
      get :failed
    end
  end

  resources :lessons do
    member do
      get :syllabus
    end
    resources :buyers
    resources :chapters


  end

  resources :posts do
    resources :post_evas
    member do
      post :upvote
      post :downvote
    end
  end


end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
  belongs_to :user
  has_many :product_lists
  belongs_to :payment

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  def create_from_cart! user, cart, *order_params
    order_params.flatten!
    orders = []
    transaction do
      order_params.each do |order_param|
      orders << user.orders.create!(total: cart.total_price,payment_id: 1 )
      end
      cart.clean!
    end
    orders
  end

  def order_ship!(params)
    if @order.aasm_state == "paid"
      @order.ship!
      ChinaSMS.use :yunpian, password: ENV["sms_ship"]
      ChinaSMS.to @order.user.cellphone, "【大赛加油站】您购买的#{@order.product_lists.first.product_name}:已被#{params[:carriage_method]}揽收，#{params[:carriage_no]}，愿她以火箭般的速度飞到您手中！目前物流动态功能尚在开发中。期待[大赛加油站]成为你5票中的1票：http://t.cn/RSSdARt"
      if @order.update_columns carriage_no: params[:carriage_no], carriage_method: params[:carriage_method]
        return "success!"
      else
        return "出错啦~"
      end
    else
      return "当前订单非待发货状态哦"
    end
  end

  def self.create_order!(params, order_params)
    address = current_user.addresses.find(params[:address_id])
    order = current_user.orders.new(order_params)
    order.carriage = current_cart.carriage_price
    order.total = current_cart.total_price + order.carriage
    order.save!
      if order.save
        current_cart.cart_items.each do |cart_item|
           if cart_item.is_selected?
             cart_item.subproduct.update_column :quantity, cart_item.subproduct.quantity - cart_item.quantity
             product_list = ProductList.new
             product_list.order_id = order.id
             product_list.product_name = cart_item.subproduct.product.title
             product_list.product_price = cart_item.subproduct.price
             product_list.quantity = cart_item.quantity
             product_list.address = address.address
             product_list.cellphone = address.cellphone
             product_list.contact_name = address.contact_name
             product_list.subproduct = cart_item.subproduct.subtitle
             product_list.product_id = cart_item.subproduct.product_id
             product_list.lists_image = cart_item.subproduct.subproduct_image.thumb
             product_list.save!
           end
        end
          current_cart.clean!
          return order.token
      else
         return false
      end
  end

  def self.generate_order!(params, current_user)
    subproduct = Subproduct.find(params[:subproduct_id])
    address = current_user.addresses.find(params[:address_id])
    quantity = params[:quantity].to_i
    order = current_user.orders.new
       order.total = subproduct.price * quantity + subproduct.carriage
       order.carriage = subproduct.carriage
       order.save!
       if order.save
          subproduct.update_column :quantity, subproduct.quantity - quantity
          product_list = ProductList.new
          product_list.order_id = order.id
          product_list.product_name = subproduct.product.title
          product_list.product_price = subproduct.price
          product_list.quantity = quantity
          product_list.address = address.address
          product_list.cellphone = address.cellphone
          product_list.contact_name = address.contact_name
          product_list.subproduct = subproduct.subtitle
          product_list.product_id = subproduct.product_id
          product_list.lists_image = subproduct.subproduct_image.thumb
          product_list.save!
       end
    return order.token
  end

  def self.generate_lesson_order(params)
    lesson = Lesson.find(params[:lesson_id])
    if lesson.present?
      order = Order.new
        order.total = lesson.price
        order.user = current_user
        order.of_lesson = true
        order.lesson_id = lesson.id
        order.save
        product_list = ProductList.new
          product_list.order = order
          product_list.product_name = lesson.title
          product_list.product_price = lesson.price
          product_list.lists_image = lesson.minor_image.thumb
          product_list.quantity = 1
          product_list.save!
      return order.token
    end
  end

  def generate_pay!(current_user)
    payment = Payment.new
      payment.total_money = self.total
      payment.user = current_user
      payment.save!
      if payment.save
        if self.is_paid?
          redirect_to order_path(self.token), alert: "该订单已支付！"
        else
          self.payment = payment
          self.save!
        end
      end
    return payment.payment_no
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipping
    end

    event :deliver do
      transitions from: :shipping, to: :shipped
    end

    event :return_good do
      transitions from: :shipped, to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :auth_user

  def index
    @orders = current_user.orders.order("id DESC")
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancel_order!
    redirect_to :back, notice: '订单已关闭！'
  end

  def shipped
    @order = Order.find(params[:id])
    @order.deliver!
    redirect_to :back
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :admin_required
  layout "admin"

  def index
    @orders = Order.order("id DESC")
  end

  def show
    @order = Order.find(params[:id])
    @product_lists = @order.product_lists
  end

  def ship_page
    @order = Order.find(params[:id])
    if @order.aasm_state != "paid"
      redirect_to :back, alert: "此订单非待发货状态哦~"
    end
  end

  def ship
     @order = Order.find(params[:id])
     redirect_to :back, notice: @order.order_ship!(params)
  end

  def shipped
    @order = Order.find(params[:id])
    @order.deliver!
    redirect_to :back
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancel_order!
    redirect_to :back, notice: "order canceled!"
  end

  def return
    @order = Order.find(params[:id])
    @order.return_good!
    redirect_to :back
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order_by_token, only: [:show, :pay_with_wechat, :pay_with_alipay]
  layout 'product'

  def build_order
    @subproduct = Subproduct.find(params[:subproduct_id])
    @amount = params[:amount]
  end

  def create
    if order_token = Order.create_order!(params, order_params)
      redirect_to generate_pay_payments_path(:id => order_token)
    else
      redirect_to :back, notice: "生成订单失败，请稍后客服~"
    end
  end

  def order_create
    order_token = Order.generate_order!(params, current_user)
    redirect_to generate_pay_payments_path(:id => order_token)
  end

  def lesson_order_create
    order_token = Order.generate_lesson_order(params)
    redirect_to lesson_generat_pay_payments_path(:id => order_token)
  end

  def show
   @product_lists = @order.product_lists
   @evaluation = Evaluation.new
  end

  def pay_with_wechat
    @order.set_payment_with!("wechat")
    @order.make_payment!
    redirect_to order_path(@order.token), notice: "使用微信成功完成付款！"
  end

  def pay_with_alipay
    @order.set_payment_with!"alipay"
    @order.make_payment!
    redirect_to order_path(@order.token),notice: "使用支付宝成功完成付款!"
  end

  def apply_to_cancel
    @order = Order.find(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    redirect_to :back, notice: "已提交申请！"
  end

  private
  def order_params
     params.require(:order).permit(:total, :user_id, :created_at, :updated_at, :token, :is_paid, :payment_method, :aasm_state, :payment_id, :carriage, :of_lesson, :lesson_id, :payment_id)
  end

  def find_order_by_token
    @order = Order.find_by_token(params[:id])
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def render_order_paid_state(order)
    if order.is_paid?
      "(已付款)"
    else
      "(未付款)"
    end
  end

  def render_order_status(order)
    case order.aasm_state
    when 'order_placed'
      "未付款"
    when 'paid'
      "等待发货"
    when 'shipping'
      "已发货"
    when 'shipped'
      "已完成"
    when 'order_cancelled'
      "订单已关闭"
    when 'good_returned'
      "已退货"
    end
  end
end

app/views/admin/orders/_state_option.html.erb
<div style="padding:10px; float:right;">
    <% case order.aasm_state %>
    <% when "order_placed" %>
    <%= link_to("取消订单",cancel_admin_order_path(order), class:"btn btn-info btn-sm", method: :post)%>
    <% when "paid" %>
    <%= link_to("取消订单", cancel_admin_order_path(order),class:"btn btn-info btn-sm", method: :post)%>
    <%= link_to("出货",ship_admin_order_path(order), class:"btn btn-info btn-sm", method: :post)%>
    <% when "shipping" %>
    <%= link_to("到货", shipped_admin_order_path(order), class:"btn btn-info btn-sm", method: :post)%>
    <% when "shipped" %>
    <%= link_to("退货",return_admin_order_path(order), class:"btn btn-info btn-sm", method: :post)%>
    <% when "order_cancelled" %>
    <span class="label label-success">订单已取消</span>
    <% when "good_returned" %>
    <span class="label label-success">已退货</span>
    <% end %>
</div>

app/views/admin/orders/index.html.erb
<h2>订单列表</h2>

<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>用户</th>
      <th style="width:100px">支付号</th>
      <th>ID</th>
      <th>生成时间</th>
      <th>支付时间</th>
      <th>状态</th>
      <th>运费</th>
      <th>商品名</th>
      <th>分类</th>
      <th>数量</th>
      <th>价格</th>
      <th>收货地址</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |o| %>
    <% count = o.product_lists.count %>
    <tr>
      <td rowspan="<%= count %>"><%= o.user.username %> / <%= o.user.cellphone %> </td>
      <td rowspan="<%= count %>" style="width:100px">
        <% if o.payment.present? %>
        <%= o.payment.payment_no %>
        <% else %>
        订单无付款号
        <% end %>
      </td>
      <td rowspan="<%= count %>"><%= o.id %></td>
      <td rowspan="<%= count %>"><%= o.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <% if o.payment_at.present? %>
      <td rowspan="<%= count %>"><%= o.payment_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <% else %>
      <td rowspan="<%= count %>">未支付</td>
      <% end %>
      <td rowspan="<%= count %>"><%= o.aasm_state %></td>
      <td rowspan="<%= count %>"><%= o.carriage %></td>
      <% if o.product_lists.count == 1 %>
        <% o.product_lists.each_with_index do |p, index| %>
          <td><%= p.product_name %></td>
          <td><%= p.subproduct %></td>
          <td><%= p.quantity %></td>
          <td><%= p.product_price %></td>
          <td><%= p.address %>/<%= p.contact_name %>/<%= p.cellphone %></td>
          <td><%= link_to "我要发货", ship_page_admin_order_path(o), class: "btn btn-success" %></td>
        <% end %>
      </tr>
    <% else %>
        <% o.product_lists.each_with_index do |p, index| %>
        <% if index == 0 %>
          <td><%= p.product_name %></td>
          <td><%= p.subproduct %></td>
          <td><%= p.quantity %></td>
          <td><%= p.product_price %></td>
          <td><%= p.address %>/<%= p.contact_name %>/<%= p.cellphone %></td>
          <td><%= link_to "我要发货", ship_page_admin_order_path(o), class: "btn btn-success" %></td>
         </tr>
      <% else %>
      <tr>
        <td><%= p.product_name %></td>
        <td><%= p.subproduct %></td>
        <td><%= p.quantity %></td>
        <td><%= p.product_price %></td>
        <td><%= p.address %>/<%= p.contact_name %>/<%= p.cellphone %></td>
        <td><%= link_to "我要发货", ship_page_admin_order_path(o), class: "btn btn-success" %></td>
      </tr>
    <% end %>
    <% end %>

    <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/ship_page.html.erb
<div class="container">
  <h5>当前订单号：[<%= @order.id %>]</h5>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>商品名</th>
        <th>分类</th>
        <th>运费</th>
        <th>收货地址</th>
      </tr>
    </thead>
    <tbody>
      <% @order.product_lists.each do |p| %>
      <tr>
        <td><%= p.product_name  %></td>
        <td><%= p.subproduct %></td>
        <td><%= @order.carriage %></td>
        <td><%= p.address %>/<%= p.contact_name %>/<%=p.cellphone %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


<hr>
  <h4>我要发货</h4>


  <hr>

  <%= form_tag(ship_admin_order_path(@order), method: "post") do %>
    <%= label_tag(:carriage_method, " 快递公司:") %>
    <%= text_field_tag(:carriage_method) %>
    <%= label_tag(:carriage_no, "运单号:") %>
    <%= text_field_tag(:carriage_no) %>
    <%= submit_tag("提交") %>
  <% end %>
</div>

app/views/admin/orders/show.html.erb
<div class="row">
    <div class="col-md-12">

        <h2>订单明细(<%= render_order_paid_state(@order) %>)</h2>
        <%= render "state_option", order: @order %>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>商品明细</th>
                    <th>单价</th>
                    <th>数量</th>
                </tr>
            </thead>
            <tbody>
                <% @product_lists.each do |product_list| %>
                <tr>
                    <td><%= product_list.product_name%></td>
                    <td><%= product_list.product_price%></td>
                    <td><%= product_list.quantity%></td>

                </tr>
                <% end %>
            </tbody>
        </table>

        <div class="total clearfix">
            <span class="pull-right">
                总计
                <%= @order.total %>
                CNY
            </span>
        </div>

        <hr/>
        <h2>寄送资讯</h2>

        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>订购人</td>
                </tr>
                <tr>
                    <td><%= @order.billing_name %>
                        -
                        <%= @order.billing_address %></td>
                </tr>
                <tr>
                    <td>收件人</td>
                </tr>
                <tr>
                    <td><%= @order.shipping_name %>
                        -
                        <%= @order.shipping_address %></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>