config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  #
  get "welcome" => "welcome#index"
  get "test" => "welcome#test"


  # 用户注册和登录登出
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout
  resources :cellphone_tokens, only: [:create]
  # mount RuCaptcha::Engine => "/rucaptcha"


  namespace :admin do
    resources :users
    resources :slider_photos do
      member do
      post :hide
      post :public
      end
    end
    
    resources :categories
    resources :products do
      resources :subproducts do
        member do
          post :update_weight
        end
      end
      resources :product_params
      resources :product_photos
    end

    resources :orders do
      member do
        get :ship_page
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    resources :lessons do
      resources :buyers
      resources :chapters
      resources :posts do
        member do
          post :update_weight
        end
      end

    end
  end



  resources :categories

  resources :products do
    member do
      post :add_to_cart
    end

    resources :evaluations do
      resources :evaluation_photos
    end
  end

  resources :carts do
    collection do
      delete :clean
        get :checkout
        post :update_cart
    end
  end

  resources :addresses do
    member do
      put :set_default_address
    end
  end

  resources :cart_items

  resources :orders do
    collection do
      post :build_order
      post :order_create
      post :lesson_order_create
    end
    member do
    post :pay_with_wechat
    post :pay_with_alipay
    post :apply_to_cancel
    post :order_create

  end
  end

  namespace :account do
    resources :orders do
      member do
        post :cancel
        post :shipped
      end
    end
  end

  resources :evaluations do
    resources :evaluation_photos
  end

  resources :payments, only: [:index] do
    member do
      post :create_payment
      get :create_payment
      post :get_payment_status
    end
    collection do
      get :generate_pay
      get :lesson_generat_pay
      post :pay_return
      post :pay_notify
      get :pay_notify
      get :pay_return
      post :test
      get :success
      get :failed
    end
  end

  resources :lessons do
    member do
      get :syllabus
    end
    resources :buyers
    resources :chapters


  end

  resources :posts do
    resources :post_evas
    member do
      post :upvote
      post :downvote
    end
  end


end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :cart_items
  has_many :subproducts, through: :cart_items, source: :subproduct

  def add_product_to_cart(subproduct, amount)
    ci = cart_items.build
    ci.subproduct = subproduct
    ci.quantity = amount.to_i
    ci.save
  end

  def update_quantity(subproduct, amount)
    ci = cart_items.find_by_subproduct_id(subproduct)
    ci.quantity += amount.to_i
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.is_selected?
        if cart_item.subproduct.price.present?
          sum += cart_item.subproduct.price * cart_item.quantity
        end
      end
    end
    sum
  end

  def carriage_price
    sum = []
    cart_items.each do |cart_item|
      if cart_item.is_selected?
        sum << cart_item.subproduct.carriage
      end
    end
    sum.max
  end

  def update_cart!(params)
    params.delete("utf8")
    params.delete("authenticity_token")
    params.delete("select-item")
    self.cart_items.each do |cart_item|
      cart_item.is_selected = false
      cart_item.save
    end
    params.each do |k, v|
      if k.to_i != 0
        selected_item = current_cart.cart_items.find(k.to_i)
        selected_item.is_selected = true
        selected_item.quantity = v["quantity"]
        selected_item.save
      end
    end
  end

  def clean!
    self.cart_items.where(:is_selected => true).destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :auth_user
  layout 'product'

  def clean
    current_cart.cart_items.destroy_all
    redirect_to :back, alert: "Deleted!"
  end

  def checkout
    @order = Order.new
  end

  def update_cart
    current_cart.update_cart!(params)
    redirect_to checkout_carts_path
  end

  def random_product
    @product = Product.order("RANDOM()").limit(3)
  end
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/views/carts/checkout.html.erb
<div class="checkout-html">
<div class="container">
  <h1><%= @subproduct_id %></h1>
  <h2><%= @amount %></h2>
  <%= form_tag orders_path, method: :post, class: "create-order-form" do %>

  <div class="page-header">
    <h4>选择收货地址</h4>
  </div>
  <div id="address_list"></div>

  <div class="require-order">
    <h4>确认订单信息</h4>
    <hr>

    <div class="order-require-nav">
      <div class="row">
        <div class="col-sm-5 col-sm-offset-1">
          商品信息
        </div>
        <div class="col-sm-2 text-center">单价</div>
        <div class="col-sm-2 text-center">数量</div>
        <div class="col-sm-2 text-center">小计</div>
      </div>
    </div>

    <% carriage_total = [] %>
    <% current_cart.cart_items.each do |cart_item| %>
      <% if cart_item.is_selected? %>
      <% carriage_total << cart_item.subproduct.carriage %>
      <div class="order-require-item">
        <div class="row">
          <div class="col-sm-6">
            <div class="col-sm-2">
              <%= image_tag cart_item.subproduct.subproduct_image, class: "img-responsive" %>
            </div>
              <div class="col-sm-5">
                <%= cart_item.subproduct.product.title %>
              </div>
              <div class="col-sm-5">
                <p>已选分类：<%= cart_item.subproduct.subtitle %></p>
              </div>
            </div>
            <div class="col-sm-6 text-center">
              <div class="col-sm-4">
                <%= cart_item.subproduct.price %>
              </div>
              <div class="col-sm-4">
                <%= cart_item.quantity %>
              </div>
              <div class="col-sm-4 subtotal">
                <%= cart_item.subproduct.price * cart_item.quantity %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>

        <div class="carriage">
          <div class="row">
            <p>运送方式：<span class="bc-1">普通快递</span>快递费：<span class="carriage-price"><%= carriage_total.max %></span></p>
          </div>
        </div>

        <div class="total-money">
          <div class="row">
            <h5>合计（含运费）<span class="total">￥<%= current_cart.total_price + carriage_total.max %></span></h5>
          </div>
        </div>

        <div class="row order-require ">
          <div class="col-sm-4 col-sm-offset-8">
            <div class="detail clearfix">
              <p class="total-price">实付款：<span class="total-price-2"><span>￥</span><%= current_cart.total_price + carriage_total.max %></span></p>
              <p class="address-1">寄送至：</p><span class="require-address"></span>
              <p class="contact-1">收件人：<span class="require-contact"></span><span class="require-cellphone"></span></p>
            </div>
            <div class="btn col-sm-6">
              <%= link_to carts_path, class: "btn btn-default" do  %>
              <i class="fa fa-reply" aria-hidden="true"></i>返回购物车
              <% end %>
            </div>
            <div class="btn col-sm-6">
              <i style="display: none;" class="fa fa-spinner fa-spin fa-fw"></i>
                <input type="submit" value="确认订单" class="btn btn-danger btn-lg require-helper-1"/>
                <span style="display: none;" class="btn btn-danger btn-lg require-helper-2">确认订单</span>
            </div>
          </div>
        </div>
      </div>
      <% end %>
</div>
</div>


  <%= content_for :javascripts do %>
    <script>



      $(".require-helper-2").click(function(){
        alert("请选择收货地址！");
      })

      $.get('/addresses', function(data) {
        $('#address_list').html(data);
      })

      $(".create-order-btn").click(function(){
        $(".fa-spinner").css("display", "block");
      })



    </script>
  <% end %>

app/views/carts/index.html.erb
  <div class="container carts-index">
    <div class="row">
      <h1>购物车</h1>
    <div class="cart-nav-top clearfix">

      <p>已选商品（不含运费）<span class="cart-item-total-price cart-item-total-price-2"><%= render_cart_total_price(current_cart) %></span>
          <%= link_to("清空购物车", clean_carts_path, method: :delete, class:"btn btn-danger pull-right", "data-confirm": "你确定要清空购物车吗?")%>
      </p>
    </div>
    </div>

    <div class="cart-navbar clearfix">
      <div class="row">
        <div class="col-sm-6">
          <div class="bc-1 col-sm-3">全选</div>
          <div class="bc-2 col-sm-9">商品信息</div>
        </div>
        <div class="col-sm-6 text-center">
          <div class="bc-3 col-sm-3">单价</div>
          <div class="bc-4 col-sm-3">数量</div>
          <div class="bc-5 col-sm-3">金额</div>
          <div class="bc-6 col-sm-3">操作</div>
        </div>
      </div>
    </div>

          <%= form_tag("/carts/update_cart", method: "post") do %>
          <% current_cart.cart_items.each do |cart_item| %>

            <div class="cart-item row">
              <div class="col-sm-6">
                <div class="col-sm-3">
                  <div class="bc-1 col-sm-2">
                    <% if cart_item.is_selected? %>
                    <input class="cart-item-select" id="cart-item-<%= cart_item.id %>" type="checkbox" name="<%= cart_item.id %>[id]" value="<%= cart_item.id %>" checked="true">
                    <% else %>
                    <input class="cart-item-select" id="cart-item-<%= cart_item.id %>" type="checkbox" name="<%= cart_item.id %>[id]" value="<%= cart_item.id %>">
                    <% end %>
                  </div>
                  <div class="bc-2 col-sm-10">
                    <% if cart_item.subproduct.product.main_product_photo.product_image.present? %>
                    <%= image_tag(cart_item.subproduct.subproduct_image, class:"img-responsive")%>
                  <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"img-responsive" )%>
                    <% end %>
                  </div>
                </div>
                <div class="bc-3 col-sm-5">
                  <%= cart_item.subproduct.product.title %>
                </div>
                <div class="bc-4 col-sm-4">
                  已选分类 ：<%= cart_item.subproduct.subtitle%>
                </div>
              </div>
              <div class="col-sm-6 text-center">
                <div class="bc-5 col-sm-3">
                  <% if cart_item.subproduct.present? %>
                   ￥<%= cart_item.subproduct.price %>
                   <% else %>
                   未找到价格
                   <% end %>
                </div>
                <div class="bc-6 col-sm-3">
                  <div id="cart-item-quantity-<%= cart_item.id %>">
                    <% if cart_item.is_selected? %>
                    <input id="quantity-<%= cart_item.id %>" class="quantity-input" data_step="1" name="<%= cart_item.id %>[quantity]" data_edit="true" data_min="1" data_max="523698" data_digit="0" value="<%= cart_item.quantity %>"/>
                    <% else %>
                    <input id="quantity-<%= cart_item.id %>" class="quantity-input" data_step="1" disabled="disabled" name="<%= cart_item.id %>[quantity]" data_edit="true" data_min="1" data_max="523698" data_digit="0" value="<%= cart_item.quantity %>"/>
                    <% end %>
                  </div>
                  <!-- 一个辅助的隐藏表单 -->
                  <input type="hidden" id="quantity-help-<%= cart_item.id %>" name="<%= cart_item.id %>[quantity]" value="<%= cart_item.quantity %>">
                </div>
                <div class="bc-7 col-sm-3">
                <% if cart_item.is_selected? %>
                <span>￥</span><span id="cart-item-price-<%= cart_item.id %>" class="selected-item-price cart-item-price"><%= cart_item.subproduct.price * cart_item.quantity %></span>
                <% else %>
                <span>￥</span><span id="cart-item-price-<%= cart_item.id %>" class="cart-item-price"><%= cart_item.subproduct.price * cart_item.quantity %></span>
                <% end %>
                </div>
                <div class="bc-8 col-sm-3">
                  <%= link_to(content_tag(:i,"", class: "fa fa-trash"), cart_item_path(cart_item),method: :delete, data:{confirm: "确定吗？"})%>
                </div>
              </div>
          <!-- hidden-form -->
          <input type="hidden" name="item-price-<%= cart_item.subproduct.price %>" disabled="true" value="<%= cart_item.subproduct.price %>">
          </div>
          <% end %>

      <div class="total clearfix">
        <div class="all-select">
          <input type="hidden" id="select_help" value="0">
          <input class="cart-item" type="checkbox" name="select-item" value="" >
          <p>全选</p>
        </div>


      <% if current_user %>
      <div class="checkout-btn checkout-btn-1">
        <input id="checkout-btn-1" type="submit" value="去结算" class="btn btn-success btn-lg"/>
      </div>
      <div style="display: none;" class="checkout-btn checkout-btn-2">
        <input id="checkout-btn-2" type="button" value="去结算" class="btn btn-success btn-lg"/>
      </div>
      <% else %>
      <div class="checkout-btn checkout-btn-3">
        <input id="checkout-btn-3" type="button" value="去结算" class="btn btn-success btn-lg"/>
      </div>
      <% end %>
      <% end %>
      <div class="total-price">
        <p>合计（不含运费）：<span class="cart-item-total-price"><%= render_cart_total_price(current_cart) %></span></p>
      </div>

        </div>
    </div>
  </div>





  <script>
    <% current_cart.cart_items.each do |cart_item| %>
    // 更改数量时
    $("#cart-item-quantity-<%= cart_item.id %>").click(function(){
      var price = $('input[name="item-price-<%= cart_item.subproduct.price %>"]').val();
      var quantity = $("#quantity-<%= cart_item.id %>").val();
      var max_quantity = <%= cart_item.subproduct.quantity %>;

      if (quantity > max_quantity){
        $("#quantity-<%= cart_item.id %>").val(max_quantity);
        alert("输入在数量大于当前商品的库存，已更改为最大可买数量！");
      }
      $("#cart-item-price-<%= cart_item.id %>").html(price * quantity);
      var total = 0;
        $(".selected-item-price").each(function(i){
          total += parseFloat($(this).html());
        });
      $(".cart-item-total-price").html(total);
      // 赋值给辅助提交表单
      $("#quantity-help-<%= cart_item.id %>").val(quantity);
    })
    // 更改数量时判断
    $("#cart-item-quantity-<%= cart_item.id %>").change(function(){
      var price = $('input[name="item-price-<%= cart_item.subproduct.price %>"]').val();
      var quantity = $("#quantity-<%= cart_item.id %>").val();
      var max_quantity = <%= cart_item.subproduct.quantity %>;

      if (quantity > max_quantity){
        $("#quantity-<%= cart_item.id %>").val(max_quantity);
        alert("输入在数量大于当前商品的库存，已更改为最大可买数量！");
      }
      $("#cart-item-price-<%= cart_item.id %>").html(price * quantity);
      var total = 0;
        $(".selected-item-price").each(function(i){
          total += parseFloat($(this).html());
        });
      $(".cart-item-total-price").html(total);
      $("#quantity-help-<%= cart_item.id %>").val(quantity);
    })



// 选择时为表单生效
$("#cart-item-<%= cart_item.id %>").click(function(){
  var option = $("#quantity-<%= cart_item.id %>").prop("disabled");
  // alert(option);

  if (option == ""){
    // alert(1);
    $("#quantity-<%= cart_item.id %>").prop("disabled", "disabled");
    $("#cart-item-price-<%= cart_item.id %>").removeClass('selected-item-price');
    var total = 0;
      $(".selected-item-price").each(function(i){
        total += parseFloat($(this).html());
      });
    $(".cart-item-total-price").html(total);
    $("#quantity-help-<%= cart_item.id %>").prop("disabled", "disabled");
    // 判断当前选择是否为空
    if($(".cart-item-total-price").html() == "0"){
      $(".checkout-btn-2").css("display", "block");
      $(".checkout-btn-1").css("display", "none");
    }else{
      $(".checkout-btn-2").css("display", "none");
      $(".checkout-btn-1").css("display", "block");
    }
  }else{
    // alert(2);
    $("#quantity-<%= cart_item.id %>").prop("disabled", false);
    $("#cart-item-price-<%= cart_item.id %>").addClass('selected-item-price');
    var total = 0;
      $(".selected-item-price").each(function(i){
        total += parseFloat($(this).html());
      });
    $(".cart-item-total-price").html(total);
    $("#quantity-help-<%= cart_item.id %>").prop("disabled",false);
    // 判断当前选择是否为空
    if($(".cart-item-total-price").html() == "0"){
      $(".checkout-btn-2").css("display", "block");
      $(".checkout-btn-1").css("display", "none");
    }else{
      $(".checkout-btn-2").css("display", "none");
      $(".checkout-btn-1").css("display", "block");
    }
  }
})

    <% end %>


    $(".all-select").click(function(){
      var current_value = $("#select_help").val();

      if (current_value == 0 ){
        // 全选
        $(".cart-item-price").addClass('selected-item-price');
        $(".cart-item-select").prop('checked', true);
        var total = 0;
          $(".cart-item-price").each(function(i){
            total += parseFloat($(this).html());
          });
        $(".cart-item-total-price").html(total);
        $("#select_help").val(1);
        $(".quantity-input").prop("disabled", false);

        // 判断当前选择是否为空
        if($(".cart-item-total-price").html() == "0"){
          $(".checkout-btn-2").css("display", "block");
          $(".checkout-btn-1").css("display", "none");
        }else{
          $(".checkout-btn-2").css("display", "none");
          $(".checkout-btn-1").css("display", "block");
        }
      }else{
        // 不选
        $(".cart-item-select").prop("checked",false);
        $("#select_help").val(0);
        $(".cart-item-total-price").html("0");
        $(".selected-item-price").removeClass('selected-item-price');
        $(".quantity-input").prop("disabled", "disabled");



        // 判断当前选择是否为空
        if($(".cart-item-total-price").html() == "0"){
          $(".checkout-btn-2").css("display", "block");
          $(".checkout-btn-1").css("display", "none");
        }else{
          $(".checkout-btn-2").css("display", "none");
          $(".checkout-btn-1").css("display", "block");
        }

      }
    })


    // 选择为空时的提示
    $("#checkout-btn-2").click(function(){
      alert("请选择要要结算的商品~");
    })
    // 未登录时，提示登入
    $("#checkout-btn-3").click(function(){
      alert("请先登入哦~");
    })


  </script>

app/views/carts/update_cart.html.erb
<%= @cart.id %>