config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  #
  get "welcome" => "welcome#index"
  get "test" => "welcome#test"


  # 用户注册和登录登出
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout
  resources :cellphone_tokens, only: [:create]
  # mount RuCaptcha::Engine => "/rucaptcha"


  namespace :admin do
    resources :users
    resources :slider_photos do
      member do
      post :hide
      post :public
      end
    end
    
    resources :categories
    resources :products do
      resources :subproducts do
        member do
          post :update_weight
        end
      end
      resources :product_params
      resources :product_photos
    end

    resources :orders do
      member do
        get :ship_page
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    resources :lessons do
      resources :buyers
      resources :chapters
      resources :posts do
        member do
          post :update_weight
        end
      end

    end
  end



  resources :categories

  resources :products do
    member do
      post :add_to_cart
    end

    resources :evaluations do
      resources :evaluation_photos
    end
  end

  resources :carts do
    collection do
      delete :clean
        get :checkout
        post :update_cart
    end
  end

  resources :addresses do
    member do
      put :set_default_address
    end
  end

  resources :cart_items

  resources :orders do
    collection do
      post :build_order
      post :order_create
      post :lesson_order_create
    end
    member do
    post :pay_with_wechat
    post :pay_with_alipay
    post :apply_to_cancel
    post :order_create

  end
  end

  namespace :account do
    resources :orders do
      member do
        post :cancel
        post :shipped
      end
    end
  end

  resources :evaluations do
    resources :evaluation_photos
  end

  resources :payments, only: [:index] do
    member do
      post :create_payment
      get :create_payment
      post :get_payment_status
    end
    collection do
      get :generate_pay
      get :lesson_generat_pay
      post :pay_return
      post :pay_notify
      get :pay_notify
      get :pay_return
      post :test
      get :success
      get :failed
    end
  end

  resources :lessons do
    member do
      get :syllabus
    end
    resources :buyers
    resources :chapters


  end

  resources :posts do
    resources :post_evas
    member do
      post :upvote
      post :downvote
    end
  end


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :subproducts, -> { order(weight: 'desc') },
    dependent: :destroy
  has_one :max_subproduct, -> { order(weight: 'desc') },
    class_name: :Subproduct

  has_one :min_subproduct, -> { order(weight: 'asc') },
    class_name: :Subproduct

  has_many :evaluations, dependent: :destroy

  has_many :product_params, dependent: :destroy

  has_many :product_photos, -> { order(weight: 'desc') },
    dependent: :destroy
  has_one :main_product_photo, -> { order(weight: 'desc') },
    class_name: :ProductPhoto

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :admin_required
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def new
    @product = Product.new
    @root_categories = Category.all
  end

  def show
    @subproducts = @product.subproducts
    @subproduct = Subproduct.new
    @product_params = @product.product_params
    @product_param = ProductParam.new
    @product_photos = @product.product_photos
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path,notice:"create success!"
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path,notice:"update success!"
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to :back, warning: "Deleted!"
    end
  end


  private
  def find_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id, :slogan)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :auth_user
    layout 'product'

  def show

    @product = Product.find(params[:id])
    @rand_products = Product.order("RANDOM()").limit(3)
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @subproduct = @product.subproducts.find(params[:subproduct_id])
    if !current_cart.subproducts.include?(@subproduct)
      current_cart.add_product_to_cart(@subproduct, params[:amount])
      render :json => { :title => @subproduct.subtitle, :message => "ok", :cart_count => current_cart.reload.cart_items.count }
    else
      current_cart.update_quantity(@subproduct, params[:amount])
      render :json => { :title => @subproduct.subtitle, :message => "ok", :cart_count => current_cart.reload.cart_items.count, :test => params[:amount] }
    end
  end

end

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>

<%= simple_form_for [:admin,@product] do |f| %>
<div class="group"><%= f.input :title%></div>
<div class="group"><%= f.input :description%></div>
<div class="group"><%= f.input :slogan %></div>

<%= f.submit "submit" %>
<% end %>

app/views/admin/products/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>Product List</h1>
        <div class="pull-right">
            <%= link_to("新增产品", new_admin_product_path, class:"btn btn-primary")%>
        </div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Product Pic</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                <% @products.each do |product| %>
                <tr>
                    <td><%= product.id %></td>

                    <td><%= link_to product.title, admin_product_path(product)%></td>
                    <td><%= product.price %></td>
                    <td><%= link_to("Edit", edit_admin_product_path(product))%></td>
                    <td><%= link_to("Deleted", admin_product_path(product), method: :delete, "data-confirm":   "亲！确定要删除吗？？？请三思呐！") %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/products/new.html.erb
<h2>New Product</h2>

<%= simple_form_for [:admin, @product] do |f| %>
<div class="group"><%= f.input :title%></div>
<div class="group"><%= f.input :description%></div>
<div class="group"><%= f.input :slogan %></div>
<select name="product[category_id]">
  <option></option>
  <% @root_categories.each do |category| %>
    <option value="<%= category.id %>" <%= @product.category_id == category.id ? 'selected' : '' %>><%= category.title %></option>

  <% end -%>
</select>
<%= f.submit 'Submit', data:{disable_with: "Submiting..."},class:"btn btn-primary"%>

<% end %>

app/views/admin/products/show.html.erb
<h1>【当前商品】：<%= @product.title %></h1>

<h4>累计评价： <%= @product.evaluation_count %></h4>
<h4>累计销量： <%= @product.sales_count %></h4>
<p>商品介绍： <%= @product.description %></p>
<hr>

<h2>【商品的小分类】</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>名称</th>
      <th>原价/现价/促销活动名</th>
      <th>运费</th>
      <th>发货地</th>
      <th>库存</th>
      <th>优先级</th>
      <th>缩略图</th>
      <th>选项</th>
    </tr>
  </thead>
  <tbody>
<% @subproducts.each do |subproduct| %>
  <tr>
    <td><%= subproduct.subtitle %></td>
    <td><%= subproduct.msrp %> / <%= subproduct.price %> / <%= subproduct.activity %></td>
    <td><%= subproduct.carriage %></td>
    <td><%= subproduct.place %></td>
    <td><%= subproduct.quantity %></td>
    <td>
      <%= form_tag update_weight_admin_product_subproduct_path(@product, subproduct), method: :post do %>
        <input type="text" value="<%= subproduct.weight %>" name="weight" />
        <%= submit_tag "更新", class: "btn btn-default btn-xs" %>
      <% end %>
    </td>
    <% if subproduct.subproduct_image.present? %>
    <td><%= image_tag(subproduct.subproduct_image.thumb.url, class: "img-responsive") %></td>
    <% end %>
    <td>
      <%= link_to("Delete", admin_product_subproduct_path(@product, subproduct), method: :delete, "data-confirm": "Are you sure?", class: "btn btn-primary") %>
      <%= link_to "编辑", edit_admin_product_subproduct_path(@product, subproduct), class: "btn btn-success" %>
    </td>
  </tr>
<% end %>
</tbody>
</table>
<hr>
<h3>新增小分类</h3>
<%= simple_form_for [:admin,@product, @subproduct] do |f| %>
<%= f.input :subtitle %>
<%= f.input :msrp %>
<%= f.input :price %>
<%= f.input :activity %>
<%= f.input :carriage %>
<%= f.input :place %>
<%= f.input :quantity %>
<%= f.input :subproduct_image, as: :file %>
<%= f.submit "submit" %>
<% end %>
<hr>
<h2>【商品的一些参数信息】</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>内容</th>
      <th>权重</th>
      <th>选项</th>
    </tr>
  </thead>
  <tbody>
    <% @product_params.each do |product_param| %>
    <tr>
      <td><%= product_param.content %></td>
      <td><%= product_param.weight %></td>
      <td><%= link_to("Delete", admin_product_product_param_path(@product, product_param), method: :delete, "data-confirm": "Are you sure?", class: "btn btn-primary") %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<h3>新增参数信息</h3>
<%= simple_form_for [:admin, @product, @product_param] do |f| %>
  <%= f.input :content %>
  <%= f.input :weight %>
  <%= f.submit "submit" %>
<% end %>
<hr>
<h1>【图片管理】</h1>


  <div class="pull-right" style="display: flex;">
    <%= form_tag admin_product_product_photos_path(product_id: @product), method: :post, enctype: "multipart/form-data", style: "display: flex;", class: "form-horizontal" do %>
      <input type="file" name="images[]" multiple class="image-input" />
      <%= submit_tag "上传", class: "btn btn-success" %>
    <% end -%>
  </div>


<div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>图片</th>
        <th>权重</th>
        <th>选项</th>
      </tr>
    </thead>
    <tbody>
      <% @product_photos.each do |product_photo| %>
        <tr>
          <td><%= product_photo.id %></td>
          <td><%= image_tag(product_photo.product_image.thumb.url, class: "img-responsive") %></td>
          <td>
            <%= form_tag admin_product_product_photo_path(@product, product_photo), method: :put do %>
              <input type="text" value="<%= product_photo.weight %>" name="weight" />
              <%= submit_tag "更新", class: "btn btn-default btn-xs" %>
            <% end -%>
          </td>
          <td align="right">
            <%= link_to "删除", admin_product_product_photo_path(@product, product_photo), method: :delete, 'data-confirm': "确认删除吗?", class: "btn btn-primary" %>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>
<hr>
<br>
<br>
<br>
<br>
<br>