config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  #
  get "welcome" => "welcome#index"
  get "test" => "welcome#test"


  # 用户注册和登录登出
  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout
  resources :cellphone_tokens, only: [:create]
  # mount RuCaptcha::Engine => "/rucaptcha"


  namespace :admin do
    resources :users
    resources :slider_photos do
      member do
      post :hide
      post :public
      end
    end
    
    resources :categories
    resources :products do
      resources :subproducts do
        member do
          post :update_weight
        end
      end
      resources :product_params
      resources :product_photos
    end

    resources :orders do
      member do
        get :ship_page
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    resources :lessons do
      resources :buyers
      resources :chapters
      resources :posts do
        member do
          post :update_weight
        end
      end

    end
  end



  resources :categories

  resources :products do
    member do
      post :add_to_cart
    end

    resources :evaluations do
      resources :evaluation_photos
    end
  end

  resources :carts do
    collection do
      delete :clean
        get :checkout
        post :update_cart
    end
  end

  resources :addresses do
    member do
      put :set_default_address
    end
  end

  resources :cart_items

  resources :orders do
    collection do
      post :build_order
      post :order_create
      post :lesson_order_create
    end
    member do
    post :pay_with_wechat
    post :pay_with_alipay
    post :apply_to_cancel
    post :order_create

  end
  end

  namespace :account do
    resources :orders do
      member do
        post :cancel
        post :shipped
      end
    end
  end

  resources :evaluations do
    resources :evaluation_photos
  end

  resources :payments, only: [:index] do
    member do
      post :create_payment
      get :create_payment
      post :get_payment_status
    end
    collection do
      get :generate_pay
      get :lesson_generat_pay
      post :pay_return
      post :pay_notify
      get :pay_notify
      get :pay_return
      post :test
      get :success
      get :failed
    end
  end

  resources :lessons do
    member do
      get :syllabus
    end
    resources :buyers
    resources :chapters


  end

  resources :posts do
    resources :post_evas
    member do
      post :upvote
      post :downvote
    end
  end


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :subproducts, -> { order(weight: 'desc') },
    dependent: :destroy
  has_one :max_subproduct, -> { order(weight: 'desc') },
    class_name: :Subproduct

  has_one :min_subproduct, -> { order(weight: 'asc') },
    class_name: :Subproduct

  has_many :evaluations, dependent: :destroy

  has_many :product_params, dependent: :destroy

  has_many :product_photos, -> { order(weight: 'desc') },
    dependent: :destroy
  has_one :main_product_photo, -> { order(weight: 'desc') },
    class_name: :ProductPhoto

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :admin_required
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def new
    @product = Product.new
    @root_categories = Category.all
  end

  def show
    @subproducts = @product.subproducts
    @subproduct = Subproduct.new
    @product_params = @product.product_params
    @product_param = ProductParam.new
    @product_photos = @product.product_photos
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path,notice:"create success!"
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path,notice:"update success!"
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to :back, warning: "Deleted!"
    end
  end


  private
  def find_product
    @product = Product.find(params[:id])
  end
  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id, :slogan)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :auth_user
    layout 'product'

  def show

    @product = Product.find(params[:id])
    @rand_products = Product.order("RANDOM()").limit(3)
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @subproduct = @product.subproducts.find(params[:subproduct_id])
    if !current_cart.subproducts.include?(@subproduct)
      current_cart.add_product_to_cart(@subproduct, params[:amount])
      render :json => { :title => @subproduct.subtitle, :message => "ok", :cart_count => current_cart.reload.cart_items.count }
    else
      current_cart.update_quantity(@subproduct, params[:amount])
      render :json => { :title => @subproduct.subtitle, :message => "ok", :cart_count => current_cart.reload.cart_items.count, :test => params[:amount] }
    end
  end

end

app/views/products/_product_detail.html.erb
<div class="product-params">
  <div class="row product-params-bc">
  <% if @product.product_params.present? %>
  <div class="params-slogan">商品参数</div>
  <% @product.product_params.each do |product_param| %>
  <div class="params-item col-sm-3">
    <%= product_param.content %>
  </div>
  <% end %>
  <% end %>
</div>
</div>
<br>
<div class="intro-markdown">
  <%= raw @product.description %>
</div>

app/views/products/_product_evaluation.html.erb
<div class="row product-eva">
  <% if @product.evaluations.present? %>
  <p class="eva-title">
    商品评价
  </p>
  <% end %>
</div>

<% if @product.evaluations.present? %>
    <% @product.evaluations.each do |evaluation| %>
    <div class="row">
      <div class="col-sm-8">
        <div class="eva-bc-1">
          <p><%= evaluation.description %></p>
        </div>
        <div class="eva-bc-2">
          <% if evaluation.evaluation_photos.present? %>
          <% evaluation.evaluation_photos.each do |evaluation_photo| %>
          <div class="image-item">
            <%= image_tag(evaluation_photo.evaluation_image.thumb, class: "img-responsive") %>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="evc-bc-3">
          <% if evaluation.explain.present? %>
          <p><%= evaluation.explain %></p>
          <% end %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="col-sm-6">
          <p>所选分类<span><%= evaluation.subtitle %></span></p>
        </div>
        <div class="col-sm-6">
          <p><%= evaluation.user.id %></p>
          <!-- Todo 增加用户头像 -->
        </div>
      </div>
    </div>
    <% end %>

<% else %>
    <p class="eva-nil">此商品暂无评价</p>
<% end %>

app/views/products/_product_images.html.erb
<div id="magnifier">
  <div class="small-box">
    <img src="<%= @product.main_product_photo.product_image.medium %>" alt="#">
    <span class="hover"></span>
  </div>
  <div class="thumbnail-box">
    <a href="javascript:;" class="btn btn-prev"></a>
    <a href="javascript:;" class="btn btn-next"></a>
    <div class="list">
      <ul class="wrapper">
        <% @product.product_photos.each_with_index do |p, index| %>
          <% if index == 0 %>
            <li class="item item-cur" data-src2="<%= p.product_image.big %>" data-src="<%= p.product_image.medium %>" ><img src="<%= p.product_image.thumb %>" alt="#"></li>
          <% else %>
            <li class="item" data-src2="<%= p.product_image.big %>" data-src="<%= p.product_image.medium %>"><img src="<%= p.product_image.thumb %>" alt="#"></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="big-box">
    <img src="<%= @product.main_product_photo.product_image.big %>" alt="#">
  </div>
</div>
<script>
  $(function () {

    $('#magnifier').magnifier();

  });
</script>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="subnavbar">
    <div class="container">
      <%= link_to "首页", root_path %> > <%= @product.category.title %> > <%= @product.title %>
    </div>
  </div>
</div>
<h1><% select_id = 1 %></h1>
<div class="container">
  <div class="row">
    <div class="col-sm-5">
      <% if @product.product_photos.present? %>
      <%= render "product_images" %>
      <% else %>
      <p>暂无图片哦！</p>
      <% end %>
    </div>
    <div class="col-sm-7 product-bc-2">
      <h4><%= @product.title %></h4>
      <p class="slogan"><%= @product.slogan %></p>
      <div class="price-bc">
        <div class="price-bc-2">
          <div class="sale_count">
            <p>累计销量</p>
            <p class="p2"><%= @product.sales_count %></p>
          </div>
          <div class="eva_count">
            <p>累计评价</p>
            <p class="p2"><%= @product.evaluation_count %></p>
          </div>
          <% if @product.subproducts.count != 1 %>
            <p>价格 <span id="msrp">￥ <%= @product.min_subproduct.msrp %> - <%= @product.max_subproduct.msrp %></span></p>
            <p>促销价 <span id="price"><span class="price-icon">￥</span><%= @product.min_subproduct.price %> - <%= @product.max_subproduct.price %></span>
            <s></s><span class="label label-danger"><%= @product.max_subproduct.activity %></span></p>
          <% else %>
            <p>价格 <span id="msrp">￥ <%= @product.max_subproduct.msrp %></span></p>
            <p>促销价 <span id="price"><span class="price-icon">￥</span><%= @product.max_subproduct.price %></span>
            <s></s><span class="label label-danger"><%= @product.max_subproduct.activity %></span></p>
          <% end %>
        </div>
      </div>
      <div class="carriage">
        <p><span>运费</span> 由 <%= @product.max_subproduct.place %> 发出 <span class="trace">快递:</span>
          <span id="carriage"><%= @product.max_subproduct.carriage %></span></p>
      </div>

      <div class="select-alert">
        <div class="alert-log">
           <span><i class="fa fa-times" id="close-alert" aria-hidden="true"></i></span>
          <p>请确认您要的商品信息</p>
        </div>
      <div class="select_product">
        <div class="row">
          <div class="col-sm-2">
            <p>选择分类</p>
          </div>
          <% max_quantity = [] %>
          <div class="col-sm-10">
            <% @product.subproducts.each do |subproduct| %>
            <% max_quantity << subproduct %>
            <div class="select_item" id="select_item-<%= subproduct.id %>">
              <%= image_tag(subproduct.subproduct_image.thumb, class: "img-responsive") %>
              <h5><%= subproduct.subtitle %></h5>
            </div>
            <div id="select-hidden-<%= subproduct.id %>" class="slect-hidden" style="display: none;">
              <% select_id = subproduct.id %>
            </div>
            <% end %>
            <input name="select-active" type="hidden" id="select-active1" style="width:200px;" value=""/>
          </div>
        </div>
      </div>
      </div>
        <div class="row">
          <div class="quantity-group">
          <div class="btn-item btn-item-1 ">
            <p class="quantity-slogan">数量</p>
            <%= form_tag build_order_orders_path(:subproduct_id => select_id), method: :post do %>
            <div class="select-quantity">
              <input id="5" data_step="1" name="amount" data_edit="true" data_min="1" data_max="523698" data_digit="0" value="1"/>
            </div>
            <p class="quantity-item-2">库存<span id="subproduct-quantity"><%= @product.min_subproduct.quantity %></span>件</p>
          </div>
        </div>
      </div>

      <!-- 以下是两个购物按钮 -->
          <div class="join-cart-btn clearfix">
          <div class="btn-item btn-item-2 col-sm-6 text-center">


            <%= link_to add_to_cart_product_path(@product), :class => "to-cart btn btn-danger" do %>
             <i class="fa fa-cart-plus" aria-hidden="true"></i>
             <i style="display: none;" class="fa fa-refresh to-cart-icon fa-spin fa-lg fa-fw" aria-hidden="true"></i> 加入购物车
             <% end %>

          </div>


          <div class="btn-item btn-item-3 col-sm-6 text-center">
            <% if current_user %>
            <div class="btn-item-3-1">
              <span class="btn btn-danger">
                立即购买
              </span>
            </div>
            <div style="display: none;" class="btn-item-3-2">
              <%= submit_tag "立即购买", class: "btn btn-danger" %>
            </div>

            <div style="display: none;" class="btn-item-3-3">
              <span class="btn btn-danger">
                立即购买
              </span>
            </div>

          <% else %>
          <div class="btn-item-3-4 alert-login">
            <span class="btn btn-danger">
              立即购买
            </span>
          </div>
          <% end %>
          </div>
          <% end %>
        </div>

    <!-- 按钮结束 -->

      <div class="payment-method">
        <p>支付方式：在线付款，支持信用卡、支付宝</p>
        <p>提示： 暂不支持退款</p>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="row product-bc-3">
     <!-- 以下是随机推荐商品 -->
    <div class="col-sm-2 rand_product">
      <div class="rand_product-slogan">
        <h4>随机推荐商品</h4>
      </div>
      <% @rand_products.each do |rand_product| %>
      <%= link_to product_path(rand_product) do  %>
      <div class="row rand_product-item">
        <% if rand_product.main_product_photo.present? %>
        <%= image_tag(rand_product.main_product_photo.product_image.small, class: "img-responsive") %>
        <% else %>
        <%= image_tage("http://placehold.it/200x200&text=No Pic") %>
        <% end %>
        <p class="rand_product-title"><%= rand_product.title %></p>
        <p class="rand_product-price"><span>￥</span><%= rand_product.min_subproduct.price %></p>
      </div>
      <% end %>
      <% end %>
    </div>
    <div class="col-sm-10">
      <!-- 以下是bootstrap-tab -->
      <div>
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active test-btn"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">商品介绍</a></li>
            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">评价</a></li>
          </ul>
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="home"><%= render "product_detail" %></div>
            <div role="tabpanel" class="tab-pane fade" id="profile"><%= render "product_evaluation" %></div>
          </div>
      </div>
    </div>
  </div>
</div>




<!-- 基本页面结束 -->






<!-- 以下是生成购物车的提示modal -->
<div class="modal fade" tabindex="-1" id="shopping_cart_modal">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div class="success-img text-center">
          <img src="http://bucket1.hongliang.fun/blog/2017-05-30-Snip20170530_1.png" alt="join-cart-success">
        </div>
        <h5 class="text-center">加入购物车成功</h5>

        <div class="media">
          <div class="media-left">
            <a href="javascript:;">
              <%= image_tag @product.main_product_photo.product_image.thumb, class: 'media-object', alt: "title" %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= @product.title %></h4>
            <div class="row">
              <div class="col-sm-6">
                <p>分类：<span id="modal-subproduct"></span></p>
              </div>
              <div class="col-sm-6">
                <p>数量：<span id="modal-amount"></span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-sm-6">
            <button type="button" class="btn btn-default" data-dismiss="modal">继续购物</button>
          </div>
          <div class="col-sm-6">
            <%= link_to "查看购物车", carts_path, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- 以下是contact-top条： -->
<div class="contact-topv" id="contacttop">
  <div class=" container-fluid contact-top">
    <div class="container">
      <div class="product-image">
        <%= image_tag(@product.main_product_photo.product_image.thumb, class: "img-responsive")%>
      </div>
      <div class="product-title">
        <h4><%= @product.title %></h4>
      </div>
      <div class="contact-top-btn">
        <div onclick="goselect()" class="buy-btn">
          <span class="btn btn-danger">
            立即购买
          </span>
        </div>
        <div onclick="goselect()" class="join-cart">
          <span class="btn btn-danger">
            <i class="fa fa-cart-plus" aria-hidden="true"></i>加入购物车
          </span>
        </div>
      </div>
    </div>
  </div>
</div>





<!-- 以下是javascript -->
<script>
// 以下是选择分类的js
<% @product.subproducts.each do |subproduct| %>
$("#select_item-<%= subproduct.id %>").click(function(){
  $(".select_item").css("border", "2px solid #f1f1f1"),
  $(".slect-hidden").css("display", "none"),
  $(this).css("border", "2px solid #e4393c"),
  $("#msrp").html("￥<%= subproduct.msrp %>"),
  $("#price").html("<span class='price-icon'>￥</span><%= subproduct.price %>"),
  $("#carriage").html("<%= subproduct.carriage %>"),
  $(".btn-item-3-1").css("display", "none"),
  $(".btn-item-3-2").css("display", "block"),
  $("#select-hidden-<%= subproduct.id %>").css("display", "block"),
  $("#select-active1").val("<%= subproduct.id %>"),
  $("#subproduct-quantity").html("<%= subproduct.quantity %>"),
  $('input[name="amount"]').attr("data_max", "<%= subproduct.quantity %>")
  var input_quantity = $("#5").val();
  var current_quantity = $("#5").attr("data_max");

  if (current_quantity < input_quantity){
    $(".btn-item-3-2").css("display", "none"),
    $(".btn-item-3-3").css("display", "block");

  }
})
<% end %>

// 以下是加入购物车的js
 $(".to-cart").click(function(evt){
    evt.preventDefault();
    var url = $(this).attr("href");
    var amount = $('input[name="amount"]').val();
    var id = $('input[name="select-active"]').val();
    var input_quantity = $("#5").val();
    var current_quantity = $("#5").attr("data_max");

     if (id == ""){
       $(".select-alert").css("border", "3px solid #e4393c"),
       $(".select-alert").css("padding", "17px"),
       $(".alert-log").slideDown()
     }else if ( current_quantity > input_quantity){
         $.ajax({
           url: url,
           method: "POST",
           data: { subproduct_id: id, amount: amount },
           dataType: 'json',
           beforeSend: function(){
              $(".to-cart-icon").css("display", "inline-block");
            },
           success: function(data){
            $("#modal-subproduct").html(data["title"]);
            $("#modal-amount").html(amount);
            $("#shopping_cart_modal").modal();
            $("#cart-count").html(data["cart_count"]);
           },
           complete: function(){
             $(".to-cart-icon").css("display", "none");

           }
         });
     }else{
       alert("您输入的数量大于库存数量，请返回修改~~~~~XD");
     }
 })


 // 以下是绑定了几个事件的btn
 $(".btn-item-3-1").click(function(){
   $(".select-alert").css("border", "3px solid #e4393c"),
   $(".select-alert").css("padding", "17px"),
   $(".alert-log").slideDown()
 })
 $(".btn-item-3-3").click(function(){
   alert("您输入的数量大于库存数量，请返回修改~~~~~XD");
 })
 $(".alert-login").click(function(){
   alert("请先登录哦~");
 })

// 以下是检测输入数量是否大于库存的js

  $("#5").on('change', function(){
    var input_quantity = $(this).val();
    var current_quantity = $(this).attr("data_max");

    if (current_quantity != 523698){
      if (input_quantity > current_quantity){
        $(this).val(current_quantity),
        alert("您输入的数量大于现有库存哦~~~~~XD，已为您");
      }else{
        $(".btn-item-3-3").css("display", "none");
        $(".btn-item-3-2").css("display", "block");

      }
    }

  });

// 以下是提示选择商品信息
// $(".select-alert")




// 以下是contacttop的事件
$("#close-alert").click(function(){
  $(".select-alert").css("border", "0"),
  $(".select-alert").css("padding", "0"),
  $(".alert-log").css("display", "none")
})
$(".contact-top-btn").click(function(){


  $('html,body').animate({scrollTop: '0px'}, 800); // 平滑滚动

  setTimeout(function () {
    $(".alert-log").slideDown(),
    $(".select-alert").css("border", "3px solid #e4393c"),
    $(".select-alert").css("padding", "17px")
  }, 1000);
})




// 以下是bootstrap-tab
$('#myTabs a[href="#profile"]').tab('show') // Select tab by name
$('#myTabs a:first').tab('show') // Select first tab
$('#myTabs a:last').tab('show') // Select last tab
$('#myTabs li:eq(2) a').tab('show') // Select third tab (0-indexed)
$('#myTabs a').click(function (e) {e.preventDefault()
$(this).tab('show')
})

// 以下是下拉时显示导航条 contacttop
window.onscroll = function () {
  scrollFunction()
};

function scrollFunction() {

  var x = document.getElementById("contacttop")
  if (document.body.scrollTop > 568 || document.documentElement.scrollTop > 568) {
    x.className = "show";
  } else {
    x.className = x.className.replace("show", "");
  }
}



</script>